name: eux-avslutt-rinasaker
ingress: https://eux-avslutt-rinasaker.intern.nav.no

database:
  name: eux-avslutt-rinasaker-db
  tier: db-custom-1-3840

kafka:
  pool: nav-prod
  topics:
    eux-rina-document-events-v1: eessibasis.eux-rina-document-events-v1
    eux-rina-case-events-v1: eessibasis.eux-rina-case-events-v1

cluster:
  fss: prod-fss
  gcp: prod-gcp

application:
  eux-rina-terminator-api:
    name: eux-rina-terminator-api
    endpoint: http://eux-rina-terminator-api
    scope: api://prod-gcp.eessibasis.eux-rina-terminator-api/.default

  eux-avslutt-rinasaker-til-avslutning-naisjob:
    name: eux-avslutt-rinasaker-til-avslutning-naisjob

  eux-avslutt-rinasaker-sett-uvirksom-naisjob:
    name: eux-avslutt-rinasaker-sett-uvirksom-naisjob

  eux-avslutt-rinasaker-avslutt-naisjob:
    name: eux-avslutt-rinasaker-avslutt-naisjob

  eux-avslutt-rinasaker-arkiver-naisjob:
    name: eux-avslutt-rinasaker-arkiver-naisjob

  eux-avslutt-rinasaker-til-arkivering-naisjob:
    name: eux-avslutt-rinasaker-til-arkivering-naisjob

  eux-avslutt-rinasaker-slett-dokumentutkast-naisjob:
    name: eux-avslutt-rinasaker-slett-dokumentutkast-naisjob
